// Code generated by protoc-gen-go. DO NOT EDIT.
// source: identity.proto

package identity

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ParseTokenStatusCode int32

const (
	ParseTokenStatusCode_SUCCESS          ParseTokenStatusCode = 0
	ParseTokenStatusCode_INVALID          ParseTokenStatusCode = 1
	ParseTokenStatusCode_OUTDATED_ACCESS  ParseTokenStatusCode = 2
	ParseTokenStatusCode_OUTDATED_REFRESH ParseTokenStatusCode = 3
)

var ParseTokenStatusCode_name = map[int32]string{
	0: "SUCCESS",
	1: "INVALID",
	2: "OUTDATED_ACCESS",
	3: "OUTDATED_REFRESH",
}
var ParseTokenStatusCode_value = map[string]int32{
	"SUCCESS":          0,
	"INVALID":          1,
	"OUTDATED_ACCESS":  2,
	"OUTDATED_REFRESH": 3,
}

func (x ParseTokenStatusCode) String() string {
	return proto.EnumName(ParseTokenStatusCode_name, int32(x))
}
func (ParseTokenStatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_identity_7da91ae0f84b29ef, []int{0}
}

type RevokeTokenResponse_RevokeTokenStatusCode int32

const (
	RevokeTokenResponse_SUCCESS RevokeTokenResponse_RevokeTokenStatusCode = 0
	RevokeTokenResponse_FAIL    RevokeTokenResponse_RevokeTokenStatusCode = 1
)

var RevokeTokenResponse_RevokeTokenStatusCode_name = map[int32]string{
	0: "SUCCESS",
	1: "FAIL",
}
var RevokeTokenResponse_RevokeTokenStatusCode_value = map[string]int32{
	"SUCCESS": 0,
	"FAIL":    1,
}

func (x RevokeTokenResponse_RevokeTokenStatusCode) String() string {
	return proto.EnumName(RevokeTokenResponse_RevokeTokenStatusCode_name, int32(x))
}
func (RevokeTokenResponse_RevokeTokenStatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_identity_7da91ae0f84b29ef, []int{6, 0}
}

// Isssue token
type IssueTokenRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Login                string   `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueTokenRequest) Reset()         { *m = IssueTokenRequest{} }
func (m *IssueTokenRequest) String() string { return proto.CompactTextString(m) }
func (*IssueTokenRequest) ProtoMessage()    {}
func (*IssueTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_7da91ae0f84b29ef, []int{0}
}
func (m *IssueTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueTokenRequest.Unmarshal(m, b)
}
func (m *IssueTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueTokenRequest.Marshal(b, m, deterministic)
}
func (dst *IssueTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueTokenRequest.Merge(dst, src)
}
func (m *IssueTokenRequest) XXX_Size() int {
	return xxx_messageInfo_IssueTokenRequest.Size(m)
}
func (m *IssueTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IssueTokenRequest proto.InternalMessageInfo

func (m *IssueTokenRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *IssueTokenRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

type IssueTokenResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueTokenResponse) Reset()         { *m = IssueTokenResponse{} }
func (m *IssueTokenResponse) String() string { return proto.CompactTextString(m) }
func (*IssueTokenResponse) ProtoMessage()    {}
func (*IssueTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_7da91ae0f84b29ef, []int{1}
}
func (m *IssueTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueTokenResponse.Unmarshal(m, b)
}
func (m *IssueTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueTokenResponse.Marshal(b, m, deterministic)
}
func (dst *IssueTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueTokenResponse.Merge(dst, src)
}
func (m *IssueTokenResponse) XXX_Size() int {
	return xxx_messageInfo_IssueTokenResponse.Size(m)
}
func (m *IssueTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IssueTokenResponse proto.InternalMessageInfo

func (m *IssueTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *IssueTokenResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

// Parse token
type ParseTokenRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParseTokenRequest) Reset()         { *m = ParseTokenRequest{} }
func (m *ParseTokenRequest) String() string { return proto.CompactTextString(m) }
func (*ParseTokenRequest) ProtoMessage()    {}
func (*ParseTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_7da91ae0f84b29ef, []int{2}
}
func (m *ParseTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseTokenRequest.Unmarshal(m, b)
}
func (m *ParseTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseTokenRequest.Marshal(b, m, deterministic)
}
func (dst *ParseTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseTokenRequest.Merge(dst, src)
}
func (m *ParseTokenRequest) XXX_Size() int {
	return xxx_messageInfo_ParseTokenRequest.Size(m)
}
func (m *ParseTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ParseTokenRequest proto.InternalMessageInfo

func (m *ParseTokenRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *ParseTokenRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type ParseTokenResponse struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Login                string               `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Status               ParseTokenStatusCode `protobuf:"varint,3,opt,name=status,proto3,enum=identity.ParseTokenStatusCode" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ParseTokenResponse) Reset()         { *m = ParseTokenResponse{} }
func (m *ParseTokenResponse) String() string { return proto.CompactTextString(m) }
func (*ParseTokenResponse) ProtoMessage()    {}
func (*ParseTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_7da91ae0f84b29ef, []int{3}
}
func (m *ParseTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseTokenResponse.Unmarshal(m, b)
}
func (m *ParseTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseTokenResponse.Marshal(b, m, deterministic)
}
func (dst *ParseTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseTokenResponse.Merge(dst, src)
}
func (m *ParseTokenResponse) XXX_Size() int {
	return xxx_messageInfo_ParseTokenResponse.Size(m)
}
func (m *ParseTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ParseTokenResponse proto.InternalMessageInfo

func (m *ParseTokenResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ParseTokenResponse) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *ParseTokenResponse) GetStatus() ParseTokenStatusCode {
	if m != nil {
		return m.Status
	}
	return ParseTokenStatusCode_SUCCESS
}

// Revoke user tokens
type RevokeUserTokensRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeUserTokensRequest) Reset()         { *m = RevokeUserTokensRequest{} }
func (m *RevokeUserTokensRequest) String() string { return proto.CompactTextString(m) }
func (*RevokeUserTokensRequest) ProtoMessage()    {}
func (*RevokeUserTokensRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_7da91ae0f84b29ef, []int{4}
}
func (m *RevokeUserTokensRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeUserTokensRequest.Unmarshal(m, b)
}
func (m *RevokeUserTokensRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeUserTokensRequest.Marshal(b, m, deterministic)
}
func (dst *RevokeUserTokensRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeUserTokensRequest.Merge(dst, src)
}
func (m *RevokeUserTokensRequest) XXX_Size() int {
	return xxx_messageInfo_RevokeUserTokensRequest.Size(m)
}
func (m *RevokeUserTokensRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeUserTokensRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeUserTokensRequest proto.InternalMessageInfo

func (m *RevokeUserTokensRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

// Revoke token
type RevokeTokenRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeTokenRequest) Reset()         { *m = RevokeTokenRequest{} }
func (m *RevokeTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RevokeTokenRequest) ProtoMessage()    {}
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_7da91ae0f84b29ef, []int{5}
}
func (m *RevokeTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeTokenRequest.Unmarshal(m, b)
}
func (m *RevokeTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeTokenRequest.Marshal(b, m, deterministic)
}
func (dst *RevokeTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeTokenRequest.Merge(dst, src)
}
func (m *RevokeTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RevokeTokenRequest.Size(m)
}
func (m *RevokeTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeTokenRequest proto.InternalMessageInfo

func (m *RevokeTokenRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RevokeTokenRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RevokeTokenResponse struct {
	Code                 RevokeTokenResponse_RevokeTokenStatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=identity.RevokeTokenResponse_RevokeTokenStatusCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *RevokeTokenResponse) Reset()         { *m = RevokeTokenResponse{} }
func (m *RevokeTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RevokeTokenResponse) ProtoMessage()    {}
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_7da91ae0f84b29ef, []int{6}
}
func (m *RevokeTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeTokenResponse.Unmarshal(m, b)
}
func (m *RevokeTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeTokenResponse.Marshal(b, m, deterministic)
}
func (dst *RevokeTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeTokenResponse.Merge(dst, src)
}
func (m *RevokeTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RevokeTokenResponse.Size(m)
}
func (m *RevokeTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeTokenResponse proto.InternalMessageInfo

func (m *RevokeTokenResponse) GetCode() RevokeTokenResponse_RevokeTokenStatusCode {
	if m != nil {
		return m.Code
	}
	return RevokeTokenResponse_SUCCESS
}

func init() {
	proto.RegisterType((*IssueTokenRequest)(nil), "identity.IssueTokenRequest")
	proto.RegisterType((*IssueTokenResponse)(nil), "identity.IssueTokenResponse")
	proto.RegisterType((*ParseTokenRequest)(nil), "identity.ParseTokenRequest")
	proto.RegisterType((*ParseTokenResponse)(nil), "identity.ParseTokenResponse")
	proto.RegisterType((*RevokeUserTokensRequest)(nil), "identity.RevokeUserTokensRequest")
	proto.RegisterType((*RevokeTokenRequest)(nil), "identity.RevokeTokenRequest")
	proto.RegisterType((*RevokeTokenResponse)(nil), "identity.RevokeTokenResponse")
	proto.RegisterEnum("identity.ParseTokenStatusCode", ParseTokenStatusCode_name, ParseTokenStatusCode_value)
	proto.RegisterEnum("identity.RevokeTokenResponse_RevokeTokenStatusCode", RevokeTokenResponse_RevokeTokenStatusCode_name, RevokeTokenResponse_RevokeTokenStatusCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IdentifierClient is the client API for Identifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentifierClient interface {
	IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error)
	ParseToken(ctx context.Context, in *ParseTokenRequest, opts ...grpc.CallOption) (*ParseTokenResponse, error)
	RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error)
	RevokeUserTokens(ctx context.Context, in *RevokeUserTokensRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error)
}

type identifierClient struct {
	cc *grpc.ClientConn
}

func NewIdentifierClient(cc *grpc.ClientConn) IdentifierClient {
	return &identifierClient{cc}
}

func (c *identifierClient) IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error) {
	out := new(IssueTokenResponse)
	err := c.cc.Invoke(ctx, "/identity.Identifier/IssueToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identifierClient) ParseToken(ctx context.Context, in *ParseTokenRequest, opts ...grpc.CallOption) (*ParseTokenResponse, error) {
	out := new(ParseTokenResponse)
	err := c.cc.Invoke(ctx, "/identity.Identifier/ParseToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identifierClient) RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error) {
	out := new(RevokeTokenResponse)
	err := c.cc.Invoke(ctx, "/identity.Identifier/RevokeToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identifierClient) RevokeUserTokens(ctx context.Context, in *RevokeUserTokensRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error) {
	out := new(RevokeTokenResponse)
	err := c.cc.Invoke(ctx, "/identity.Identifier/RevokeUserTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentifierServer is the server API for Identifier service.
type IdentifierServer interface {
	IssueToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error)
	ParseToken(context.Context, *ParseTokenRequest) (*ParseTokenResponse, error)
	RevokeToken(context.Context, *RevokeTokenRequest) (*RevokeTokenResponse, error)
	RevokeUserTokens(context.Context, *RevokeUserTokensRequest) (*RevokeTokenResponse, error)
}

func RegisterIdentifierServer(s *grpc.Server, srv IdentifierServer) {
	s.RegisterService(&_Identifier_serviceDesc, srv)
}

func _Identifier_IssueToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentifierServer).IssueToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/identity.Identifier/IssueToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentifierServer).IssueToken(ctx, req.(*IssueTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identifier_ParseToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentifierServer).ParseToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/identity.Identifier/ParseToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentifierServer).ParseToken(ctx, req.(*ParseTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identifier_RevokeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentifierServer).RevokeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/identity.Identifier/RevokeToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentifierServer).RevokeToken(ctx, req.(*RevokeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identifier_RevokeUserTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeUserTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentifierServer).RevokeUserTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/identity.Identifier/RevokeUserTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentifierServer).RevokeUserTokens(ctx, req.(*RevokeUserTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Identifier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "identity.Identifier",
	HandlerType: (*IdentifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueToken",
			Handler:    _Identifier_IssueToken_Handler,
		},
		{
			MethodName: "ParseToken",
			Handler:    _Identifier_ParseToken_Handler,
		},
		{
			MethodName: "RevokeToken",
			Handler:    _Identifier_RevokeToken_Handler,
		},
		{
			MethodName: "RevokeUserTokens",
			Handler:    _Identifier_RevokeUserTokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity.proto",
}

func init() { proto.RegisterFile("identity.proto", fileDescriptor_identity_7da91ae0f84b29ef) }

var fileDescriptor_identity_7da91ae0f84b29ef = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x94, 0xc1, 0x4e, 0xf2, 0x40,
	0x14, 0x85, 0x29, 0xf0, 0xf3, 0xe3, 0x05, 0xb1, 0x0c, 0x18, 0x89, 0xa2, 0x91, 0xba, 0x31, 0x9a,
	0xb0, 0x80, 0xc4, 0x8d, 0xab, 0x06, 0x8a, 0x36, 0x21, 0x6a, 0x5a, 0x60, 0x83, 0x09, 0x41, 0x18,
	0xb4, 0xd1, 0xb4, 0xd8, 0x99, 0x9a, 0xf8, 0x12, 0x3e, 0x97, 0x8f, 0xe5, 0x74, 0x5a, 0x69, 0xa1,
	0x45, 0x5d, 0xe8, 0x8e, 0x7b, 0xe6, 0xcc, 0x97, 0x7b, 0xcf, 0x5c, 0x0a, 0x05, 0x63, 0x8a, 0x4d,
	0x6a, 0xd0, 0xd7, 0xfa, 0xdc, 0xb6, 0xa8, 0x85, 0xb2, 0x9f, 0xb5, 0x74, 0x0e, 0x45, 0x95, 0x10,
	0x07, 0xf7, 0xac, 0x47, 0x6c, 0x6a, 0xf8, 0xd9, 0xc1, 0x84, 0x22, 0x11, 0x52, 0x8e, 0x31, 0xad,
	0x08, 0x87, 0xc2, 0xf1, 0x86, 0xe6, 0xfe, 0x44, 0x65, 0xf8, 0xf7, 0x64, 0xdd, 0x1b, 0x66, 0x25,
	0xc9, 0x35, 0xaf, 0x90, 0x6e, 0x01, 0x85, 0x2f, 0x93, 0xb9, 0x65, 0x12, 0x8c, 0x6a, 0x90, 0x1f,
	0x4f, 0x26, 0x98, 0x90, 0x11, 0x75, 0x75, 0x1f, 0x93, 0xf3, 0x34, 0x6e, 0x45, 0x47, 0xb0, 0x69,
	0xe3, 0x99, 0x8d, 0xc9, 0x83, 0xef, 0xf1, 0xb0, 0x79, 0x5f, 0xe4, 0x26, 0x69, 0x08, 0xc5, 0x9b,
	0xb1, 0x4d, 0x96, 0x5b, 0xfb, 0x2d, 0x38, 0x05, 0x14, 0x86, 0xfb, 0xad, 0xff, 0x70, 0x70, 0x74,
	0x06, 0x19, 0x42, 0xc7, 0xd4, 0x21, 0x95, 0x14, 0x93, 0x0b, 0x8d, 0x83, 0xfa, 0x22, 0xe0, 0x80,
	0xaa, 0x73, 0x47, 0xcb, 0x9a, 0x62, 0xcd, 0x77, 0x4b, 0xa7, 0xb0, 0xa3, 0xe1, 0x17, 0x76, 0xd8,
	0x27, 0xd8, 0xe6, 0x26, 0xb2, 0x36, 0x73, 0x37, 0x5d, 0xcf, 0xfc, 0x27, 0x01, 0xbc, 0x09, 0x50,
	0x5a, 0xc2, 0xfb, 0x11, 0x5c, 0x40, 0x7a, 0xc2, 0x5a, 0xe6, 0xdc, 0x42, 0xa3, 0x19, 0x0c, 0x16,
	0x63, 0x0e, 0x6b, 0xa1, 0x69, 0x39, 0x40, 0xaa, 0xc3, 0x76, 0xec, 0x31, 0xca, 0xc1, 0x7f, 0xbd,
	0xdf, 0x6a, 0x29, 0xba, 0x2e, 0x26, 0x50, 0x16, 0xd2, 0x1d, 0x59, 0xed, 0x8a, 0xc2, 0xc9, 0x10,
	0xca, 0x71, 0xd9, 0x2d, 0xdb, 0x59, 0xa1, 0x5e, 0x0d, 0xe4, 0xae, 0xda, 0x16, 0x05, 0x54, 0x82,
	0xad, 0xeb, 0x7e, 0xaf, 0x2d, 0xf7, 0x94, 0xf6, 0x48, 0xf6, 0x1c, 0x49, 0xf6, 0x60, 0xe2, 0x42,
	0xd4, 0x94, 0x8e, 0xa6, 0xe8, 0x97, 0x62, 0xaa, 0xf1, 0x9e, 0x04, 0x50, 0xf9, 0x24, 0x33, 0x03,
	0xdb, 0x48, 0x65, 0xd5, 0x62, 0x71, 0xd1, 0x5e, 0x30, 0x64, 0xe4, 0xbf, 0xb0, 0x5b, 0x8d, 0x3f,
	0xf4, 0x02, 0x90, 0x12, 0x2e, 0x2a, 0x68, 0x3b, 0x8c, 0x8a, 0xec, 0x6e, 0x18, 0x15, 0xdd, 0x3d,
	0x86, 0xea, 0x42, 0x2e, 0x94, 0x18, 0xaa, 0xae, 0xc9, 0xde, 0x83, 0xed, 0x7f, 0xf9, 0x32, 0x8c,
	0x36, 0x00, 0x71, 0x75, 0xd7, 0x50, 0x6d, 0xf5, 0x52, 0x64, 0x0f, 0xbf, 0xe5, 0xde, 0x65, 0xf8,
	0x27, 0xa4, 0xf9, 0x11, 0x00, 0x00, 0xff, 0xff, 0x17, 0x7f, 0xf3, 0x82, 0x54, 0x04, 0x00, 0x00,
}
