version: '2'

services:
  api:
    build: './api'
    ports:
      - "8080:8080"
    volumes:
      - /opt/kpacubo/media:/opt/media
    networks:
      base:
        ipv4_address: 10.5.0.2
  api_db:
    build: './api/db'
    volumes:
      - /var/lib/mongodb/:/var/lib/mongodb
    networks:
      base:
        ipv4_address: 10.5.0.4
    
networks:
  base:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
