version: '2'

services:
<<<<<<< HEAD
=======
  nginx:
    build: './nginx'
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live:/cert
      - /opt/kpacubo:/opt/kpacubo/
    networks:
      - api
      - swagger

>>>>>>> ca98bea09b557ab0f10212a89573c51070027df3
  api:
    build: './api'
    volumes:
      - /opt/kpacubo/media:/opt/media
    networks:
<<<<<<< HEAD
      base:
        ipv4_address: 10.5.0.2
  
=======
      - api
>>>>>>> ca98bea09b557ab0f10212a89573c51070027df3
  swagger:
    build: './swagger'
    volumes:
      - ./swagger:/swagger
    environment:
      - SWAGGER_JSON=/swagger/config.json
    networks:
<<<<<<< HEAD
      base:
        ipv4_address: 10.5.0.3


  nginx:
    build: './nginx'
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - /opt/kpacubo:/opt/kpacubo/
      - /etc/letsencrypt:/cert
    networks:
      base:
        ipv4_address: 10.5.0.6

networks:
  base:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
=======
      - swagger
>>>>>>> ca98bea09b557ab0f10212a89573c51070027df3
