version: '2'

services:
  api:
    build: './api'
    volumes:
      - /opt/kpacubo/media:/opt/media
    networks:
      base:
        ipv4_address: 10.5.0.2
  
  swagger:
    build: './swagger'
    volumes:
      - ./swagger:/swagger
    environment:
      - SWAGGER_JSON=/swagger/config.json
    networks:
      base:
        ipv4_address: 10.5.0.3

  api_db:
    build: './db/ApiMongoDockerfile'
    volumes:
      - /var/lib/mongodb/:/var/lib/mongodb
    networks:
      base:
        ipv4_address: 10.5.0.4

  nginx:
    build: './nginx'
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - /opt/kpacubo:/opt/kpacubo/
      - /etc/letsencrypt:/cert
    networks:
      base:
        ipv4_address: 10.5.0.6

networks:
  base:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
