version: '2'

services:
  api:
    build: 
      dockerfile: './api/Dockerfile'
      context: '.'
    volumes:
      - /opt/kpacubo/media:/opt/media
    networks:
      base:
        ipv4_address: 10.5.0.2
  
  swagger:
    build: './swagger'
    volumes:
      - ./swagger:/swagger
    environment:
      - SWAGGER_JSON=/swagger/config.json
    networks:
      base:
        ipv4_address: 10.5.0.3

  api_db:
    build: './api/db'
    volumes:
      - /var/lib/mongodb/:/var/lib/mongodb
    networks:
      base:
        ipv4_address: 10.5.0.4
  chat_db:
    build: './chat/db'
    volumes:
      - /var/lib/mongodb_chat/:/var/lib/mongodb
    networks:
      base:
        ipv4_address: 10.5.0.9
  chat:
    build: 
      dockerfile: './chat/Dockerfile'
      context: '.'
    volumes:
      - /etc/letsencrypt:/cert
    networks:
      base:
        ipv4_address: 10.5.0.8
    ports: 
      - "2000:2000"

  nginx:
    build: './nginx'
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - /opt/kpacubo:/opt/kpacubo/
      - /etc/letsencrypt:/cert
    networks:
      base:
        ipv4_address: 10.5.0.6
  identity_service:
    build:
      dockerfile: './identity_service/Dockerfile'
      context: '.'
    networks:
      base:
        ipv4_address: 10.5.0.18


networks:
  base:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
