// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api_struct

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetUsersRequest struct {
	Uid                  []string `protobuf:"bytes,1,rep,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersRequest) Reset()         { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()    {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_14881c1518e05e29, []int{0}
}
func (m *GetUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersRequest.Unmarshal(m, b)
}
func (m *GetUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersRequest.Marshal(b, m, deterministic)
}
func (dst *GetUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersRequest.Merge(dst, src)
}
func (m *GetUsersRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersRequest.Size(m)
}
func (m *GetUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersRequest proto.InternalMessageInfo

func (m *GetUsersRequest) GetUid() []string {
	if m != nil {
		return m.Uid
	}
	return nil
}

type GetUsersResponse struct {
	Data                 []*GetUsersResponse_UserData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GetUsersResponse) Reset()         { *m = GetUsersResponse{} }
func (m *GetUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersResponse) ProtoMessage()    {}
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_14881c1518e05e29, []int{1}
}
func (m *GetUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResponse.Unmarshal(m, b)
}
func (m *GetUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResponse.Marshal(b, m, deterministic)
}
func (dst *GetUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResponse.Merge(dst, src)
}
func (m *GetUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersResponse.Size(m)
}
func (m *GetUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResponse proto.InternalMessageInfo

func (m *GetUsersResponse) GetData() []*GetUsersResponse_UserData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetUsersResponse_UserData struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Login                string   `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersResponse_UserData) Reset()         { *m = GetUsersResponse_UserData{} }
func (m *GetUsersResponse_UserData) String() string { return proto.CompactTextString(m) }
func (*GetUsersResponse_UserData) ProtoMessage()    {}
func (*GetUsersResponse_UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_14881c1518e05e29, []int{1, 0}
}
func (m *GetUsersResponse_UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResponse_UserData.Unmarshal(m, b)
}
func (m *GetUsersResponse_UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResponse_UserData.Marshal(b, m, deterministic)
}
func (dst *GetUsersResponse_UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResponse_UserData.Merge(dst, src)
}
func (m *GetUsersResponse_UserData) XXX_Size() int {
	return xxx_messageInfo_GetUsersResponse_UserData.Size(m)
}
func (m *GetUsersResponse_UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResponse_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResponse_UserData proto.InternalMessageInfo

func (m *GetUsersResponse_UserData) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GetUsersResponse_UserData) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *GetUsersResponse_UserData) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUsersRequest)(nil), "api_struct.GetUsersRequest")
	proto.RegisterType((*GetUsersResponse)(nil), "api_struct.GetUsersResponse")
	proto.RegisterType((*GetUsersResponse_UserData)(nil), "api_struct.GetUsersResponse.UserData")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, "/api_struct.API/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api_struct.API/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api_struct.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _API_GetUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_14881c1518e05e29) }

var fileDescriptor_api_14881c1518e05e29 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02, 0x32, 0xe3, 0x8b, 0x4b, 0x8a, 0x4a, 0x93, 0x4b,
	0x94, 0x94, 0xb9, 0xf8, 0xdd, 0x53, 0x4b, 0x42, 0x8b, 0x53, 0x8b, 0x8a, 0x83, 0x52, 0x0b, 0x4b,
	0x53, 0x8b, 0x4b, 0x84, 0x04, 0xb8, 0x98, 0x4b, 0x33, 0x53, 0x24, 0x18, 0x15, 0x98, 0x35, 0x38,
	0x83, 0x40, 0x4c, 0xa5, 0x99, 0x8c, 0x5c, 0x02, 0x08, 0x55, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9,
	0x42, 0x96, 0x5c, 0x2c, 0x29, 0x89, 0x25, 0x89, 0x60, 0x75, 0xdc, 0x46, 0xaa, 0x7a, 0x08, 0x43,
	0xf5, 0xd0, 0xd5, 0xea, 0x81, 0x78, 0x2e, 0x40, 0xc5, 0x41, 0x60, 0x2d, 0x52, 0x5e, 0x5c, 0x1c,
	0x30, 0x11, 0x84, 0x6d, 0x8c, 0x50, 0xdb, 0x84, 0x44, 0xb8, 0x58, 0x73, 0xf2, 0xd3, 0x33, 0xf3,
	0x24, 0x98, 0xc0, 0x62, 0x10, 0x8e, 0x90, 0x18, 0x17, 0x5b, 0x62, 0x19, 0x50, 0x43, 0x91, 0x04,
	0x33, 0x58, 0x18, 0xca, 0x33, 0xf2, 0xe3, 0x62, 0x76, 0x0c, 0xf0, 0x14, 0x72, 0xe7, 0xe2, 0x80,
	0xd9, 0x2a, 0x24, 0x8d, 0xdd, 0x2d, 0x60, 0xdf, 0x49, 0xc9, 0xe0, 0x73, 0xa8, 0x12, 0x43, 0x12,
	0x1b, 0x38, 0x8c, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x81, 0xa8, 0x62, 0x30, 0x01,
	0x00, 0x00,
}
